### ISSUE TITLE
panic: unexpected EOF

### ISSUE THREAD

**Issue by shyim** [1Password/shell-plugins#90]
### op CLI version

2.9.1

### Goal or desired behavior

Sometimes there is a weird RPC client error see below

### Current behavior

```
panic: unexpected EOF

goroutine 1 [running]:
go.1password.io/op/op-cli/command/plugin/local.(*RPCClient).provisionCredential(0xe5?, {{0xc000386da8, 0x3}, {0xc000386db0, 0xa}, 0x0}, {{0xc00003a035, 0xb}, {0xc0001a63f0, 0x25}, ...}, ...)
	/builds/dev/b5/op/op-cli/command/plugin/local/rpc.go:57 +0x185
go.1password.io/op/op-cli/command/plugin/local.rpcProvisioner.Provision(...)
	/builds/dev/b5/op/op-cli/command/plugin/local/rpc.go:163
go.1password.io/op/op-cli/command/plugin.provision(0x3bd?, {{0xc000384c40, 0x1, 0x1}, {0xc00038f2c0, 0x1f}, {0xc000383860, 0x1, 0x1}, 0xc00039c510, ...}, ...)
	/builds/dev/b5/op/op-cli/command/plugin/provision_executable.go:164 +0xa76
go.1password.io/op/op-cli/command/plugin.Run(0x0?, {{0xc000384c40, 0x1, 0x1}, {0xc00038f2c0, 0x1f}, {0xc000383860, 0x1, 0x1}, 0xc00039c510, ...}, ...)
	/builds/dev/b5/op/op-cli/command/plugin/provision_executable.go:63 +0x338
go.1password.io/op/op-cli/command.(*pluginRunCommand).Run(0xc00042e870)
	/builds/dev/b5/op/op-cli/command/plugin_run.go:180 +0xccc
go.1password.io/op/op-cli/command.Bind.func3(0xc00048b340?, {0xc0004017c0?, 0x3?, 0x4?})
	/builds/dev/b5/op/op-cli/command/command.go:71 +0x4e
github.com/spf13/cobra.(*Command).execute(0xc00048b340, {0xc000401780, 0x4, 0x4})
	/builds/dev/b5/op/vendor/github.com/spf13/cobra/command.go:844 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x15a8860)
	/builds/dev/b5/op/vendor/github.com/spf13/cobra/command.go:952 +0x39d
go.1password.io/op/op-cli/command.Execute()
	/builds/dev/b5/op/op-cli/command/root.go:327 +0x71
main.main()
	/builds/dev/b5/op/op-cli/main.go:15 +0x36
```

**Comment by shyim** [comment]
I guess it happens because I get a error the second command then fails

![image](https://user-images.githubusercontent.com/6224096/206721014-37508c72-ec80-4da7-a339-0fb93ef1f89b.png)

**Comment by AndyTitu** [comment]
> Thanks for reporting this @shyim 🙌
> 
> For my understanding: does this happen with the code from #92?

I know for sure it happens in the original shell plugin code when built locally. But I think that branch could also get the error most probably, when the plugin is locally built.

**Comment by shyim** [comment]
It seems to trigger when you call cache.Put https://github.com/1Password/shell-plugins/blob/main/plugins/aws/sts_provisioner.go#L67

**Comment by jpcoenen** [comment]
Aah, I think I know the problem. The cache does not get properly initialized for locally built plugins, which leads to assigning a value to an unintialized map. Apart from that, I'll also file an issue to make sure 1Password CLI gives more helpful output when a plugin panics because the error you've reported is very unhelpful :-)

**Comment by hculea** [comment]
Hey @shyim, have a look at [our latest CLI release](https://app-updates.agilebits.com/product_history/CLI2#v2110001)!

To the best of our knowledge, this should resolve this problem. 😄 Let us know if it persists or if we can help with anything else.

**Comment by shyim** [comment]
The error does not occur anymore :tada: . But it's also never seems to cache :see_no_evil: 

My change works once https://github.com/1Password/shell-plugins/pull/92/files, next usage gives an AWS error because a TOTP token can be used only once. And after 30 seconds it works again once.

**Comment by AndyTitu** [comment]
Update: I was able to reproduce this issue. Currently trying to figure out what the root cause is.

**Comment by shyim** [comment]
Is here any progress? :)

**Comment by AndyTitu** [comment]
The problem was identified and resolved. It was caused by an internal issue with serialising and unserialising unprintable string bytes in the plugin cache. The next release should fix this last issue you were encountering @shyim .

**Comment by AndyTitu** [comment]
Closing this because it was fixed
